// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Env.FileWatcher
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class DataCaptureService_0_Key : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"DataCaptureService_0_Key\",\"namespace\":\"Env.FileWatcher\"," +
				"\"fields\":[{\"name\":\"Key\",\"doc\":\"Key\",\"type\":\"string\"}]}");
		/// <summary>
		/// Key
		/// </summary>
		private string _Key;
		public virtual Schema Schema
		{
			get
			{
				return DataCaptureService_0_Key._SCHEMA;
			}
		}
		/// <summary>
		/// Key
		/// </summary>
		public string Key
		{
			get
			{
				return this._Key;
			}
			set
			{
				this._Key = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Key;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Key = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
